### PR TITLE
Add linter on GH

### PR DESCRIPTION
**Pull request by vasilvestre**
I enabled this here : https://github.com/vasilvestre/GWSL-Source/pull/1

### CODE REVIEW

**Comment by Pololot64** [comment]
It looks cool. How does it work?

**Comment by Pololot64** [comment]
Well it definitely hates my code. I will do some manual cleanup O_O

**Comment by vasilvestre** [comment]
These tools can be installed locally to fix it :)

**Comment by Pololot64** [comment]
Was pylint supposed to touch the bash?

**Comment by vasilvestre** [comment]
IDE touche shell using shell lint

**Comment by Pololot64** [comment]
Cool. I will try to do some fixes manually first though because some of the changes will accidentally break the code I think. But I will merge this soon. I just have some work to do.

**Pull request closed without merging**
