### PR TITLE
refactoring code with truth value test

### PR DESCRIPTION
**Pull request by idiomaticrefactoring**
refactoring code with truth value test which is more pythonic, concise, readable and efficient; how do think this change which has practical value？

### CODE REVIEW

**Comment by Pololot64** [comment]
> refactoring code with truth value test which is more pythonic, concise, readable and efficient; how do think this change which has practical value？

How practical do you think it would be?

**Comment by zjzh** [comment]
Thanks for your comments. Because we find that many developers want to make their code more pythonic. And we find that many books (e.g., writing idiomatic Python) also give some guidance to help them improve their code more pythonic. For example, using truth value test, it is more concise , efficient and pythonic. Specifically,
code='''
option={}
if option!={}:
    pass
'''
code2='''
option={}
if not option:
    pass
'''
```
import timeit
print(timeit.timeit(code,number=1000000))
print(timeit.timeit(code2,number=1000000))
Output:
0.029162790999999966
0.018889624999999965
```
we could see that refactoring truth value test, the running efficiency also is improved.

**Comment by Pololot64** [comment]
Do you realize that your code does the opposite of the original?

**Comment by zjzh** [comment]
> Do you realize that your code does the opposite of the original?

Thank you. I am confuse about it. What's the meaning of the opposite of the original?

**Comment by zjzh** [comment]
Thanks for your reminder.

**Pull request closed without merging**
