### PR TITLE
Revival of GWSL? (ongoing)

### PR DESCRIPTION
**Pull request by KMohZaid**
for context read comment from here https://github.com/Opticos/GWSL-Source/issues/180#issuecomment-2243692851

Here i was able to run it but yeah there are problems : (i had to change theme to dark from plasma theme settings bcz texts where unreadable )

#  **In this screenshot, I am using ArchWSL, BTW.**
Screenshot

I was able to build it and it worked.
unsetting WAYLAND_DISPLAY make it use vnc window rather then WSLg feature 

TODO : 
1. build script is good but may need update
2. find fix for loaded window...

Known issues :
1. helper script not work if format becomes dos from unix, so need to do something about it
2.  there is issue with wsl_tool.py -> logger not logging like earlier + issue 1 is also related
3. need to fix sed for unset command in helper script

### CODE REVIEW

**Comment by KMohZaid** [comment]
tried multiple window mode, not good even if open in separate window with taskbar hidden
image

**Comment by Pololot64** [comment]
Could you please split your changes into multiple PR's. For example, fixing the build, changing the service, editing the bash script. Doing it like this in one place is nearly impossible to test with. Also, I'd rather not disable wslg in the script. If you want to add a note about disabling wslg to the manual you can but my policy is to touch as little as possible.

**Comment by KMohZaid** [comment]
> Could you please split your changes into multiple PR's. For example, fixing the build, changing the service, editing the bash script. Doing it like this in one place is nearly impossible to test with. Also, I'd rather not disable wslg in the script. If you want to add a note about disabling wslg to the manual you can but my policy is to touch as little as possible.

splitting it into multiple PRs would be little stuff , will try that. we can instread add alias/method that user can run before starting DE, like `nowayland dbus-launch startplasma-x11` 

and yeah disabling wslg feature will be disadvantage so better not disable for all logins

**Comment by KMohZaid** [comment]
Two PRs as of now, i didnt include updated logging thing (will add this later when update every file logging to proper one, it will be time consuming)

And i will update shell script for alternative of disabling wslg, later when get time

**Comment by Pololot64** [comment]
I actually cannot accept any changes right now. GWSL is serious software used by 180,000 people and is very stable. I do not have the time to help you fix the issues with your PR. Thanks for the help, I'm glad you got it running for yourself.

**Comment by KMohZaid** [comment]
> I actually cannot accept any changes right now. GWSL is serious software used by 180,000 people and is very stable. I do not have the time to help you fix the issues with your PR. Thanks for the help, I'm glad you got it running for yourself.

You can make test branch and mess that up LoL, and it's fine. You should focus on college study

**Pull request closed without merging**
